services:
  flower:
    image: mher/flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:7.2.3-alpine

  django:
    container_name: django
    build:
      context: ./dcelery
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dcelery:/usr/src/app/
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=hyhj3hj3bhvhj3g37789hshgs
      - ALLOWED_HOSTS=localhost, 127.0.0.1
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./dcelery
    command: celery -A dcelery worker --loglevel=INFO -Q tasks,dead_letter -E
    volumes:
      - ./dcelery:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=hyhj3hj3bhvhj3g37789hshgs
      - ALLOWED_HOSTS=localhost, 127.0.0.1
    depends_on:
      - redis
      - django
      - rabbitmq

  celery-beat:
    build:
      context: ./dcelery
    command: celery -A dcelery beat --loglevel=INFO
    volumes:
      - ./dcelery:/usr/src/app/
    environment:
      - ALLOWED_HOSTS=localhost, 127.0.0.1
    depends_on:
      - django
      - rabbitmq
      - redis


  # celery2:
  #   container_name: celery2
  #   build:
  #     context: ./celeryworker
  #     dockerfile: Dockerfile
  #   command: celery -A celerytask worker --loglevel=INFO -Q queue2
  #   volumes:
  #     - ./celeryworker:/usr/src/app/
  #   depends_on:
  #     - redis
  #     - django